### ISSUE TITLE
About the Table.6 in the CAS(ME)3 paper

### ISSUE THREAD

**Issue by HarryXD2018** [jingtingEmmaLi/CAS-ME-3#1]
Hi, thanks for providing such an excellent dataset for the MEA community!

While reading the paper, I was confused by table 6 because it doesn't tell whether the evaluations were based on 4emo classes or 7emo classes explicitly. So I am just posting this issue to make sure.

**Comment by jingtingEmmaLi** [comment]
Dear [HarryXD2018](https://github.com/HarryXD2018),
Sorry about the unclearity. 
It is the 4Emo classification performance comparison.
Best,
Jingting

**Comment by HarryXD2018** [comment]
Thanks for replying! I am closing the issue.
