### ISSUE TITLE
Missing several frames from multiple subjects after data extraction

### ISSUE THREAD

**Issue by tvaranka** [jingtingEmmaLi/CAS-ME-3#3]
After extracting the data several frames are missing from multiple subjects. Could some data have been lost in the transfer? I noticed the .z11 and .z12 only have around 16GBs as opposed to the 20GB of other files, is this correct?

**Comment by tvaranka** [comment]
Contacted the authors and they have reuploaded the damaged z11 and z12 files.

There are still missing frames on around 10% of the samples, but according to the authors this is normal.

**Comment by jingtingEmmaLi** [comment]
Thanks very much for the update of @tvaranka.
Here is a further explaination for the frame drop in the database. 
Most of Part A is missing 7-8 frames at the beginning of the video, and there may be a few frames missing in the rest of the video. However, it does not have much impact on the experimental processing.
Meanwhile, the frame loss in Part B is relatively more serious. Therefore, Part B is not annotated.
